---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: flask-heroes
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rfabricio/frontend-heroes:v$BUILD_NUMBER-$GIT_BRANCH
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: flask-heroes
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer